name: screenshots
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches: main

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: 检查分支
      uses: actions/checkout@main

    - name: 执行
      run: |
        mkdir img
        curl https://image.thum.io/get/width/1280/crop/960/allowJPG/wait/20/noanimate/https://zykj.js.org -o ./img/zykj.js.org.png
    
    - name: 部署
      env:
        TZ: Asia/Shanghai
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./img
        full_commit_message: 'Updated By Github Actions'

    - name: 刷新jsd缓存
      run: curl https://purge.jsdelivr.net/gh/${{ github.repository }}/blogroll@gh-pages/

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
